name: dw3_pizza_api
description: A web server built using the shelf package.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.3.0 # ^1.6.0
  dotenv: ^3.0.0
  get_it: ^7.2.0 # ^5.0.3
  injectable: ^1.5.0 #^1.0.7
  json_annotation: ^4.1.0 # ^3.1.1
  mysql1: ^0.19.2 #^0.17.1
  shelf: ^1.2.0 # ^0.7.5
  shelf_router: ^1.1.1 # ^0.7.4
  code_builder: ^4.1.0
  

dev_dependencies:
  build_runner: ^2.1.2 # ^1.10.11
  injectable_generator: ^1.5.2 # ^1.0.7
  json_serializable: ^5.0.2 # ^3.5.1
  pedantic: ^1.9.0
  shelf_router_generator: ^1.0.1 # ^0.7.2+3
  